"""
Dynamic XML Sitemap generator with Google News extension.
"""
import logging
from datetime import datetime, timedelta
from typing import Optional

from fastapi import APIRouter, Query, Depends
from fastapi.responses import Response
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.models.article import Article, ArticleState
from app.config import get_settings

logger = logging.getLogger(__name__)
router = APIRouter()

SITE_LANGUAGE = "en"
WORDPRESS_CATEGORIES = [
    "world", "politics", "finance", "technology", "entertainment",
    "health", "sports", "education", "science", "business"
]

# Static pages (legal pages)
STATIC_PAGES = [
    "/about/", "/contact/", "/terms-of-service/", "/privacy-policy/",
    "/dmca-policy/", "/cookie-policy/", "/financial-disclaimer/", "/ai-disclosure/"
]


def escape_xml(text: Optional[str]) -> str:
    """Escape special XML characters."""
    if not text:
        return ""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )


async def get_all_published_articles(
    db: AsyncSession,
    limit: int = 5000,
    days_back: int = 2
) -> list[Article]:
    """
    Get all published articles for sitemap.
    Uses days_back to limit to recent articles for Google News sitemap.
    """
    cutoff_date = datetime.utcnow() - timedelta(days=days_back)

    stmt = (
        select(Article)
        .where(Article.state == ArticleState.PUBLISHED.value)
        .where(Article.published_at.isnot(None))
        .order_by(Article.published_at.desc())
        .limit(limit)
    )

    result = await db.execute(stmt)
    return list(result.scalars().all())


async def generate_sitemap_xml(db: AsyncSession) -> str:
    """Generate complete XML sitemap."""
    settings = get_settings()
    site_url = settings.site_url.rstrip("/")
    site_name = settings.site_name

    articles = await get_all_published_articles(db, days_back=2)

    xml = '<?xml version="1.0" encoding="UTF-8"?>\n'
    xml += '<!-- Generated by Linews - ' + datetime.utcnow().isoformat() + ' -->\n'
    xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
    xml += '        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">\n'

    # Homepage
    xml += '    <url>\n'
    xml += '        <loc>' + site_url + '/</loc>\n'
    xml += '        <changefreq>hourly</changefreq>\n'
    xml += '        <priority>1.0</priority>\n'
    xml += '    </url>\n'

    # Static pages (legal pages)
    for page in STATIC_PAGES:
        xml += '    <url>\n'
        xml += '        <loc>' + site_url + page + '</loc>\n'
        xml += '        <changefreq>monthly</changefreq>\n'
        xml += '        <priority>0.6</priority>\n'
        xml += '    </url>\n'

    # Category pages
    for category in WORDPRESS_CATEGORIES:
        xml += '    <url>\n'
        xml += '        <loc>' + site_url + '/category/' + category + '/</loc>\n'
        xml += '        <changefreq>hourly</changefreq>\n'
        xml += '        <priority>0.8</priority>\n'
        xml += '    </url>\n'

    # All published articles (last 2 days for Google News)
    for article in articles:
        published_at = article.published_at
        if published_at:
            date_str = published_at.strftime("%Y-%m-%dT%H:%M:%S+00:00")
            date_only = published_at.strftime("%Y-%m-%d")
        else:
            date_str = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S+00:00")
            date_only = datetime.utcnow().strftime("%Y-%m-%d")

        xml += '    <url>\n'
        xml += '        <loc>' + escape_xml(article.wp_url or "") + '</loc>\n'
        xml += '        <lastmod>' + date_str + '</lastmod>\n'
        xml += '        <changefreq>weekly</changefreq>\n'
        xml += '        <priority>0.6</priority>\n'

        # Google News extension
        xml += '        <news:news>\n'
        xml += '            <news:publication>\n'
        xml += '                <news:name>' + site_name + '</news:name>\n'
        xml += '                <news:language>' + SITE_LANGUAGE + '</news:language>\n'
        xml += '            </news:publication>\n'
        xml += '            <news:publication_date>' + date_only + '</news:publication_date>\n'
        xml += '            <news:title>' + escape_xml(article.meta_title or article.original_title) + '</news:title>\n'

        # Add keywords/tags if available
        if article.tags:
            keywords = ", ".join(article.tags[:5]) if isinstance(article.tags, list) else str(article.tags)
            xml += '            <news:keywords>' + escape_xml(keywords) + '</news:keywords>\n'

        xml += '        </news:news>\n'
        xml += '    </url>\n'

    xml += '</urlset>'

    return xml


async def generate_full_sitemap(db: AsyncSession) -> str:
    """Generate full sitemap without Google News extension (older articles)."""
    from sqlalchemy import and_

    cutoff_date = datetime.utcnow() - timedelta(days=2)

    stmt = (
        select(Article)
        .where(Article.state == ArticleState.PUBLISHED.value)
        .where(Article.published_at.isnot(None))
        .where(Article.published_at < cutoff_date)
        .order_by(Article.published_at.desc())
        .limit(10000)
    )

    result = await db.execute(stmt)
    older_articles = list(result.scalars().all())

    xml = '<?xml version="1.0" encoding="UTF-8"?>\n'
    xml += '<!-- Full sitemap (older articles) - ' + datetime.utcnow().isoformat() + ' -->\n'
    xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'

    for article in older_articles:
        published_at = article.published_at
        if published_at:
            date_str = published_at.strftime("%Y-%m-%dT%H:%M:%S+00:00")
        else:
            date_str = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S+00:00")

        xml += '    <url>\n'
        xml += '        <loc>' + escape_xml(article.wp_url or "") + '</loc>\n'
        xml += '        <lastmod>' + date_str + '</lastmod>\n'
        xml += '        <changefreq>monthly</changefreq>\n'
        xml += '        <priority>0.5</priority>\n'
        xml += '    </url>\n'

    xml += '</urlset>'

    return xml


@router.get("/sitemap.xml")
async def sitemap(db: AsyncSession = Depends(get_db)):
    """
    Dynamic XML sitemap for Google News and general SEO.
    Returns recent articles (last 2 days) with Google News extension.
    """
    try:
        xml = await generate_sitemap_xml(db)
        return Response(
            content=xml,
            media_type="application/xml",
            headers={
                "Cache-Control": "public, max-age=3600",
                "X-Robots-Tag": "noindex",
            }
        )
    except Exception as e:
        logger.error(f"Error generating sitemap: {e}")
        return Response(
            content='<?xml version="1.0" encoding="UTF-8"?>\n<error>Error generating sitemap</error>',
            media_type="application/xml",
            status_code=500,
        )


@router.get("/sitemap-news.xml")
async def sitemap_news(db: AsyncSession = Depends(get_db)):
    """
    Dedicated Google News sitemap.
    Returns only articles from last 2 days.
    """
    settings = get_settings()
    site_url = settings.site_url.rstrip("/")
    site_name = settings.site_name

    try:
        articles = await get_all_published_articles(db, days_back=2)

        xml = '<?xml version="1.0" encoding="UTF-8"?>\n'
        xml += '<!-- Google News Sitemap - ' + datetime.utcnow().isoformat() + ' -->\n'
        xml += '<urlset xmlns="http://www.google.com/schemas/sitemap/0.9">\n'
        xml += '    <url>\n'
        xml += '        <loc>' + site_url + '/</loc>\n'
        xml += '    </url>\n'

        for article in articles:
            published_at = article.published_at
            if published_at:
                date_str = published_at.strftime("%Y-%m-%d")
            else:
                date_str = datetime.utcnow().strftime("%Y-%m-%d")

            xml += '    <url>\n'
            xml += '        <loc>' + escape_xml(article.wp_url or "") + '</loc>\n'
            xml += '        <news:news>\n'
            xml += '            <news:publication>\n'
            xml += '                <news:name>' + site_name + '</news:name>\n'
            xml += '                <news:language>' + SITE_LANGUAGE + '</news:language>\n'
            xml += '            </news:publication>\n'
            xml += '            <news:publication_date>' + date_str + '</news:publication_date>\n'
            xml += '            <news:title>' + escape_xml(article.meta_title or article.original_title) + '</news:title>\n'

            if article.tags:
                keywords = ", ".join(article.tags[:5]) if isinstance(article.tags, list) else str(article.tags)
                xml += '            <news:keywords>' + escape_xml(keywords) + '</news:keywords>\n'

            xml += '        </news:news>\n'
            xml += '    </url>\n'

        xml += '</urlset>'

        return Response(
            content=xml,
            media_type="application/xml",
            headers={
                "Cache-Control": "public, max-age=3600",
            }
        )
    except Exception as e:
        logger.error(f"Error generating news sitemap: {e}")
        return Response(
            content='<?xml version="1.0" encoding="UTF-8"?>\n<error>Error generating news sitemap</error>',
            media_type="application/xml",
            status_code=500,
        )


@router.get("/sitemap-full.xml")
async def sitemap_full(db: AsyncSession = Depends(get_db)):
    """
    Full sitemap including older articles (without Google News extension).
    """
    try:
        xml = await generate_full_sitemap(db)
        return Response(
            content=xml,
            media_type="application/xml",
            headers={
                "Cache-Control": "public, max-age=86400",  # 24 hours
            }
        )
    except Exception as e:
        logger.error(f"Error generating full sitemap: {e}")
        return Response(
            content='<?xml version="1.0" encoding="UTF-8"?>\n<error>Error generating sitemap</error>',
            media_type="application/xml",
            status_code=500,
        )
