# encode-google-credentials.ps1
# Script để encode Google Service Account JSON thành single-line string cho .env

param(
    [Parameter(Mandatory=$false)]
    [string]$InputFile = "config\google-service-account.json",

    [Parameter(Mandatory=$false)]
    [string]$OutputFile = ".env.google-temp"
)

$ErrorActionPreference = "Stop"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Google Credentials Encoder for Linew" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if input file exists
if (-not (Test-Path $InputFile)) {
    Write-Host "ERROR: File not found: $InputFile" -ForegroundColor Red
    Write-Host ""
    Write-Host "Vui long dam bao file google-service-account.json ton tai." -ForegroundColor Yellow
    Write-Host "Ban co the:" -ForegroundColor Yellow
    Write-Host "  1. Copy file vao thu muc config/" -ForegroundColor Gray
    Write-Host "  2. Hoac chi dinh duong dan khac bang tham so -InputFile" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Vi du: .\scripts\encode-google-credentials.ps1 -InputFile 'C:\Downloads\key.json'" -ForegroundColor Gray
    exit 1
}

try {
    Write-Host "Doc file: $InputFile" -ForegroundColor Green
    
    # Read JSON file
    $jsonContent = Get-Content -Path $InputFile -Raw -Encoding UTF8
    
    # Validate JSON
    $parsed = $jsonContent | ConvertFrom-Json
    Write-Host "JSON hop le. Service Account: $($parsed.client_email)" -ForegroundColor Green
    
    # Encode to single line (remove newlines and extra spaces)
    $encoded = $jsonContent -replace '\s+', ' ' -replace '"\s*:\s*"', '":"' -replace '\s*"', '"' -replace '"\s*,\s*"', '","' -replace '\s*\}\s*', '}'
    
    # Remove all whitespace completely
    $encoded = $jsonContent -replace '[\r\n\t]', '' -replace '\s+', ''
    
    # Output to file
    $output = @"
# Google Indexing API Configuration
# Generated by encode-google-credentials.ps1

GOOGLE_SERVICE_ACCOUNT_JSON=$encoded
"@

    $output | Out-File -FilePath $OutputFile -Encoding UTF8
    
    Write-Host ""
    Write-Host "SUCCESS! Credentials da duoc encode." -ForegroundColor Green
    Write-Host ""
    Write-Host "File tam: $OutputFile" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Cach su dung:" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  Cach 1: Copy noi dung tu $OutputFile vao file .env" -ForegroundColor Gray
    Write-Host ""
    Write-Host "  Cach 2: Chay lenh sau de tu dong cap nhat .env:" -ForegroundColor Gray
    Write-Host "      .\scripts\update-env-google.ps1" -ForegroundColor White
    Write-Host ""
    Write-Host "  Cach 3: Them thu cong vao .env:" -ForegroundColor Gray
    Write-Host "      GOOGLE_SERVICE_ACCOUNT_JSON=$encoded" -ForegroundColor White
    Write-Host ""
    
    # Show preview (first 100 chars)
    Write-Host "Preview (100 ky tu dau):" -ForegroundColor Cyan
    Write-Host "  $($encoded.Substring(0, [Math]::Min(100, $encoded.Length)))..." -ForegroundColor Gray
    
} catch {
    Write-Host ""
    Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
